tasks:
  - name: web-app-dev
    command: |
      cd web-app
      cp .env.example .env
      npm install
      npm run dev
  - name: edge-functions-dev
    command: |
      cd edge_functions
      brew install supabase/tap/supabase
      supabase start
      supabase functions serve
  - name: generate-api
    command: |
      npm install @openapitools/openapi-generator-cli -g
      openapi-generator-cli generate -i docs/openapi.yaml -g typescript-axios -o ./generated-api --skip-validate-spec

ports:
  - name: edge-functions-url
    port: 54321
    visibility: public
  - name: supabase-studio
    port: 54323
    visibility: public
  - name: web-app
    port: 3000
    visibility: public
    onOpen: open-browser
