tasks:
  - name: web-app-dev
    command: |
      cd web-app
      npm install
      npm run dev
  - name: edge-functions-dev
    command: |
      cd edge_functions
      brew install supabase/tap/supabase
      supabase start
      supabase functions serve

ports:
  - name: edge-functions-url
    port: 54321
    visibility: public
  - name: supabase-studio
    port: 54322
  - name: web-app
    port: 3000
    onOpen: open-browser
