openapi: 3.0.0
info:
  title: Section API
  description: API for fetching the next section in a learning app.
  version: 1.0.0
paths:
  /section/get_next_section:
    post:
      summary: Retrieve the next section based on the provided section ID.
      requestBody:
        description: Section ID to fetch the next section.
        content:
          application/json:
            schema:
              type: object
              properties:
                section_id:
                  type: string
                  example: "12345"
              required:
                - section_id
      responses:
        '200':
          description: Successfully retrieved the next section.
          content:
            application/json:
              schema:
                type: object
                properties:
                  section_id:
                    type: string
                    example: "67890"
                  kind:
                    type: string
                    enum:
                      - STORY
                      - QUESTIONS_GAME
                    example: STORY
                  scenes:
                    type: array
                    items:
                      type: object
                      properties:
                        image_url:
                          type: string
                          example: "https://example.com/image.jpg"
                        segments:
                          type: array
                          items:
                            type: object
                            properties:
                              text:
                                type: string
                                example: "Once upon a time..."
                              sound_url:
                                type: string
                                example: "https://example.com/sound.mp3"
                        required:
                          - text
                  is_last:
                    type: boolean
                    example: false
              required:
                - section_id
                - kind
                - scenes
                - is_last
        '400':
          description: Bad request, invalid or missing section_id.
        '500':
          description: Internal server error.