name: added
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  flutter_localizations:
    sdk: flutter
  get: 4.6.6
  flutter: 
    sdk: flutter
  audioplayers: ^6.0.0


dev_dependencies: 
  flutter_lints: 4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/